### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by sberryman** [senecajs/seneca-joi#1]
I've been thinking about how to integrate Joi into seneca and here you have done it just 14 days ago! I have a few questions if you have a moment.
1. Are there plans to integrate this with [seneca-web](https://github.com/senecajs/seneca-web) or [chairo](https://github.com/hapijs/chairo) for payload validation?
2. How about response validation? That is clearly part of HAPI but I'm wondering what your thoughts are on that for seneca. I know not everything is designed to respond within seneca which would make this a bit more interesting. The main reason I ask is that it really helps with self documentation and testing within HAPI to have a schema defined using Joi for payload and response validation.
3. Joi.validate(value, schema, _[options]_) (options) can not be set based on the current design. For instance, `abortEarly` defaults to true. What if I wanted my error message (`act_invalid_msg`) to include all the errors from the message, not just the first one?

Thanks again for publishing this, in no way am I asking you to implement any of it. Simply looking for your opinion as the all knowing Mr. Seneca.

**Comment by rjrodger** [comment]
@sberryman and thank you for the suggestions! notes below
1. Generally the Seneca approach is to extend via additional plugins, so that would be the approach here. I would also observe that external HTTP payload validation is probably best done completely within the web server context, before generating Seneca msgs - that is the approach I would take
2. pretty much the same points as 1.
3. Good point! Can I be cheeky and ask you for a PR? :)

**Comment by sberryman** [comment]
Thanks for the response! I wrote that before watching your [microXchg][https://www.youtube.com/watch?v=0pfghZxlFSg] talk (along with several others from that conference). I didn't realize the best practice was to place the schema/validation/sanitization as close to the input as possible and trust data over the wire on the business logic side. It completely makes sense though.

This is for another other discussion but how do you guys handle errors in Seneca? The best advantage (in my opinion) for using HTTP with microservices is that you get very simple and consistent error handling. I saw in Nodezoo you guys use `{ ok: false, err: error }` which to me seems very fragile.
