### ISSUE TITLE
Is documentation wrong?

### ISSUE THREAD

**Issue by rlecaro2** [senecajs/seneca-joi#16]
Seneca didn't find the plugin when using `.use('joi')` but did when using `.use('seneca-joi')`.

Is the documentation outdated or I am doing something wrong?

I'm using Seneca v3.3 and Node.js v7.7.3

**Comment by KeKs0r** [comment]
I think you are right the documentation is wrong.
The problem is that seneca tries to load the string joi the following way:
```
use-plugin: Could not load plugin joi; require search list: joi, seneca-joi, ./joi, ./seneca-joi.
```

As you see it starts with just `require('joi')`, which will work, since joi is also available.

**Comment by danielo515** [comment]
I can confirm that `.use('seneca-joi')` works perfectly. I didn't tried other options, I guess they don't work. Luckily I didn't read documentation
