### ISSUE TITLE
Data modifications should be tested

### ISSUE THREAD

**Issue by StarpTech** [senecajs/seneca-joi#9]
Hi,
Joi and Parambulator has the feature to modify data. e.g 

Parambulator: default$..
Joi: .trim(), ...

I can see no tests about this scenario. I already fixed a bug for this in seneca 2.x.x thanks :)

**Comment by danielo515** [comment]
As far as I know the modified data is just ignored, which is throwing a very important feature of Joi to the trash.

**Comment by rjrodger** [comment]
it is an important feature, but we'll support in a different way: https://github.com/senecajs/seneca/issues/717
